<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>osu-pp</AssemblyName>
    <RootNamespace>OsuLocalProfiles.PpCalculator</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ppy.osu.Game" Version="2026.916.0" />
    <PackageReference Include="ppy.osu.Game.Rulesets.Osu" Version="2026.916.0" />
    <PackageReference Include="ppy.osu.Game.Rulesets.Taiko" Version="2026.916.0" />
    <PackageReference Include="ppy.osu.Game.Rulesets.Catch" Version="2026.916.0" />
    <PackageReference Include="ppy.osu.Game.Rulesets.Mania" Version="2026.916.0" />
  </ItemGroup>
</Project>
